### ISSUE TITLE
Agree on Code of Conduct to use

### ISSUE THREAD

**Issue by nubeiro** [scbcn/scbcn.github.io#7]
On a previous meetup hangout we stated we need a CoC. 

Available options (suggested by different collaborators): 
* http://2017.jsday.es/codeofconduct.html (simple & direct), suggested by @JavierCane in review of #6 
* http://berlincodeofconduct.org/es/ (trusted by a lot of communities), suggested by @JavierCane in review of #6
* http://confcodeofconduct.com/, suggested by Maria Gomez when discussing which CoC to pick.

**Comment by nubeiro** [comment]
As suggested by @JavierCane in #6 it need to be a page in itself. 
Which file should be used as template for CoC?
Do we need a stripped down, raw, black and white version of it so that it can be linked from other platforms to render when buying tickets?

**Comment by JavierCane** [comment]
Issue closed due to the agreement on the CoC to use and having it already included. Thx!
